### ISSUE TITLE
Update certificate for applet at star.mit.edu

### ISSUE THREAD

**Issue by pdpinch** [starteam/stargenetics_java#5]
via help.mit.edu

> I'm an IT person working for Kiowa school district in Colorado.  It has been brought to my attention that accessing you StarGenetics web apps (http://star.mit.edu/genetics/runapp.html) is being blocked by JAVA security due to an invalid or expired certificate.

**Comment by pwilkins** [comment]
The StarGenetics app is served from http://star.mit.edu .  It would be preferable to serve the app from an https URL.  It may even be the case that if it was served from https we could simply document the process of granting our site a security exception on their local machine.

**Comment by pwilkins** [comment]
I have requested and received an application certificate for ``stargenetics.app.mit.edu``.  The certificate will expire February 12, 2017.  Mark our calendars.
